---
- name: Clone nvim-lua/kickstart.nvim repository
  hosts: localhost
  become: false

  vars:
    nvim_repo_url: "https://github.com/nvim-lua/kickstart.nvim.git"
    nvim_config_dir: "{{ lookup('env', 'XDG_CONFIG_HOME') | default(home + '/.config', true) }}/nvim"

  tasks:
    - name: Ensure nvim config directory exists
      file:
        path: "{{ nvim_config_dir }}"
        state: directory
        mode: '0755'

    - name: Clone the nvim-lua/kickstart.nvim repository
      git:
        repo: "{{ nvim_repo_url }}"
        dest: "{{ nvim_config_dir }}"
        clone: yes
        update: no

