---
- name: Ensure servers are up-to-date
  hosts: all
  become: yes

  tasks:
    - name: Update all packages
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: yes

    - name: Ensure all packages are up-to-date
      assert:
        that:
          - ansible_facts.packages_up_to_date is defined